# -*- coding: utf-8 -*-
"""Python_Fundamentals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11IWZf--GQt9aEfOpBaW26AkWd9YBoegV

***1. PYTHON OUTPUT***
"""

print("Hello World")

print("Saika Islam")

print("hello world", 3, 4.4, "saika", sep = '/')

print("Hello", end='-')
print("World")

"""**DATA TYPES**"""

# Integer
print(8)
print(1e309)

# Decimal/Float
print(3.5)
print(1.7e308)

# Boolean
print(True)
print(False)

# String
print("Saika")

# List -> Array
print([1,2,3,4,5])

# Tuple
print((1,2,3,4,5))

# Set
print({1,2,3,4,5})

# Dictionary
print({"name": "saika","gender": "female","weight" : 40})

"""***3. VARIABLES***"""

# Static vs Dynamic
# Static vs Dynamic Binding
# stylish declaration

# C/C++
name = 'saika'
print(name)

a = 5
b = 6

print(a + b)

# Dynamic typing
#  a = 5
 # Static Typing
#  int a = 5

# Dynamic Binding
a = 5
print(a)
a = 'saika'
print(a)

# Static Binding
# int a = 5

a = 1
b = 2
c = 3
print(a,b,c)

a,b,c = 1,2,3
print(a,b,c)

a=b=c=4
print(a,b,c)

"""**COMMENTS**"""

# this is a comment
# second line
a = 4
b = 6 # like this
#second comment
print(a+b)

"""**4. KEYWORDS & IDENTIFIERS**"""

# Keywords -> if,elif,for,list,print etc

# Identifiers
# You cannot start with a digit
name1 = 'saika'
# You can use special chars -> _
_ = 'saika'
print(_)
# identifiers can not be keyword

# Take input users and store them in a variable
fnum = int(input("Enter first num: "))
snum = int(input("Enter second num: "))
# add the 2 variables
result = fnum + snum
# Print the result
print(result)

"""***5. TYPE CONVERSION***"""

# implicit and Explicit
# implicit
print(5 + 5.5)
# explicit
# str -> int
# int(4+5j)

#int to str
str(5)

# float
float(4)

"""***6. Literals***"""

a = 0b1010 #Binary Literals
b = 100 #Decimal Literal
c = 0o310 #Octral Literal
d = 0x12c # Hexadecimal Literal

# Float Literal
float_1 = 10.5
float_2 = 1.5e2
float_3 = 1.5e-3

#Complex Literal
x = 3.14j

print(a, b, c, d)
print(float_1, float_2, float_3)
print(x, x.imag, x.real)

"""***7. String***"""

string = 'This is python'
strings = "This is python"
char = "C"
multiline_str = """This is a multiline string with more than one line code."""
unicode = u"\U0001f600\U0001F606\U0001F923"
raw_str = r"raw \n string"

print(string)
print(strings)
print(char)
print(multiline_str)
print(unicode)
print(raw_str)

a = True + 4
b = False + 10

print("a :", a)
print("b :", b)

k = None
a = 5
b = 4
print("Program exe")