# -*- coding: utf-8 -*-
"""strings-lists.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eATZuXjhpdyK3B1NQ0WqXGSLNQFjxgCJ

Program - The current population of a town is 10000. The population of the town is increasing at the rate of 10% per year. You have to write a program to find out the population at the end of each of the last 10 years.
"""

curr_pop = 10000

for i in range(10,0,-1):
  print(i,curr_pop)
  curr_pop = curr_pop/1.1

# Sequence sum
# 1/1! + 2/2! + 3/3! + ...

n = int(input("enter n: "))
result = 0
fact = 1
for i in range(1,n+1):
  fact = fact * i
  result = result + i/fact
print(result)

"""Nested Loops"""

for i in range(1,5):
  for j  in range(1,5):
    print(i,j)

# enter number of rows10
# *
# **
# ***
# ****
# *****
# ******
# *******
# ********
# *********
# **********

rows = int(input("enter n: "))
for i in range(1 , rows+1):
  for j in range(1, i+1):
    print("*",end='')
  print()

# Pattern 2
# 1
# 121
# 12321
# 1234321

rows = int(input("enter n: "))
for i in range(1, rows+1):
  for j in range(1, i+1):
    print(j, end='')
  for k in range(i-1,0,-1):
    print(k,end='')
  print()

"""Loop Control Statement

*   Break
*   Continue
*   Pass



"""

# Break
lower = int(input("enter lower number : "))
upper = int(input("enter upper number : "))
for i in range(lower, upper+1):
  for j in range(2 , i):
    if i%j == 0:
       break
  else:
      print(i)

# Continue
for i in range(1 , 10):
  if i == 5:
    continue
  print(i)

# Pass
for i in range(1 , 10):
  pass

"""Strings are sequence of Characters

In Python specifically, strings are a sequence of Unicode Characters


*   Creating Strings
*   Accessing Strings
*   Adding Chars to Strings
*   Editing Strings
*   Deleting Strings
*   Operations on Strings
*   String Functions

Creating Stings
"""

s = 'Saika'
s = "Saika"
s = """Saika"""
s = str("Saika")
print(s)

"""Accessing Substrings from a String"""

# Positive indexing
s = 'Saika'
print(s[1])

# Negative indexing
s = 'Saika'
print(s[-3])

# Slicing
s = 'Saika Islam'
print(s[0:5:2])

print(s[::-1])

"""Editing and Deleting in Strings"""

s = 'Saika Islam'
# s[0] = 'A'
# Python Strings are immutable
del s
# print(s)

"""Operations on Strings
*  Arithmetic Operations
*  Relational Operations
*  Logical Operations
*  Loops on Strings
*  Membership Operations
"""

print("Saika"+ " "+ "Islam")

print("saika "*5)

"saika" == "saika"

"mumbai" > "pune"
# Lexiography

"saika" and "islam"

"saika" or "islam"

'' and "saika"

'' or "saika"

for i in "saika":
  print(i)

for i in "delhi":
  print("pune")

"S" in "Saika"

"""Common Functions
* len
* max
* min
* sorted
"""

len("Saika islam")

max("saika Islam")

min("saika islam")

sorted("saika islam", reverse=True)

"""Capitalize/Title/Upper/Lower/Swapcase"""

s = "saika islam"
s.capitalize()

s = "saika islam"
s.title()

s = "saika islam"
s.lower()

s = "saika islam"
s.upper()

s = "sAiKa IsLam"
s.swapcase()

"""Count/Find/Index"""

"my name is saika".count("a")

"my name is saika".find("x")

"my name is saika".index("a")

"""endswith/startswith"""

"my name is saika".startswith("my")

"my name is saika".endswith("my")

"""Format"""

name = "saika"
gender = "female"
"my name is {} and gender is {}".format(name , gender)

"""isalnum/ isalpha/ isdigit/ isidentifier"""

"saika123".isalnum()

"saika".isalpha()

"1234".isdigit()

"name_1".isidentifier()

"""Split/Join"""

"my name is saika islam".split()

"_".join(['my', 'name', 'is', 'saika', 'islam'])

"""Replace"""

"my name is saika islam".replace("saika","sania")

"""Strip"""

"saika                  ".strip()

"""Example Programs"""

# Find the length of a given string without using the len() function
s = input('enter the string: ')

counter = 0

for i in s:
  counter += 1

print('length of string is',counter)

# Extract username from a given email.
# Eg if the email is nitish24singh@gmail.com
# then the username should be nitish24singh
s = input('enter the email')

pos = s.index('@')
print(s[0:pos])

# Count the frequency of a particular character in a provided string.
# Eg 'hello how are you' is the string, the frequency of h in this string is 2.
s = input('enter the email')
term = input('what would like to search for')

counter = 0
for i in s:
  if i == term:
    counter += 1

print('frequency',counter)

# Write a program which can remove a particular character from a string.
s = input('enter the string')
term = input('what would like to remove')

result = ''

for i in s:
  if i != term:
    result = result + i

print(result)

# Write a program that can check whether a given string is palindrome or not.
# abba
# malayalam
s = input('enter the string')
flag = True
for i in range(0,len(s)//2):
  if s[i] != s[len(s) - i -1]:
    flag = False
    print('Not a Palindrome')
    break

if flag:
  print('Palindrome')

# Write a program to count the number of words in a string without split()
s = input('enter the string')
L = []
temp = ''
for i in s:

  if i != ' ':
    temp = temp + i
  else:
    L.append(temp)
    temp = ''

L.append(temp)
print(L)

# Write a python program to convert a string to title case without using the title()
s = input('enter the string')

L = []
for i in s.split():
  L.append(i[0].upper() + i[1:].lower())

print(" ".join(L))
# Write a program that can convert an integer to string.
number = int(input('enter the number'))

digits = '0123456789'
result = ''
while number != 0:
  result = digits[number % 10] + result
  number = number//10

print(result)
print(type(result))
